# main repository: Venuchander/fintrack
name: Trigger Contributor Tracking

on:
  pull_request:
    types: [closed]

jobs:
  trigger-tracking:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Extract PR details
      id: pr-details
      run: |
        echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
        echo "pr_author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
        echo "pr_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT
        echo "repo_owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "repo_name=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
        
    - name: Trigger contributor tracking
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: Venuchander/fintrack-contributor-tracker
        event-type: pr-merged
        client-payload: |
          {
            "pr_number": ${{ steps.pr-details.outputs.pr_number }},
            "pr_author": "${{ steps.pr-details.outputs.pr_author }}",
            "pr_url": "${{ steps.pr-details.outputs.pr_url }}",
            "repo_owner": "${{ steps.pr-details.outputs.repo_owner }}",
            "repo_name": "${{ steps.pr-details.outputs.repo_name }}"
          }
          
    - name: Log tracking trigger
      run: |
        echo "Triggered contributor tracking for:"
        echo "- PR: #${{ steps.pr-details.outputs.pr_number }}"
        echo "- Author: ${{ steps.pr-details.outputs.pr_author }}"
        echo "- Repository: ${{ steps.pr-details.outputs.repo_owner }}/${{ steps.pr-details.outputs.repo_name }}"